<thead>
	<tr>
		<th mapping="promoabrule_id">promoabrule_id</th>
		<th mapping="promoabrule_code">promoabrule_code</th>
		<th mapping="promoabrule_name">promoabrule_name</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 50px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="width: 90px; border-bottom: 1px solid #000000">Code</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Name</td>
	</tr>
</thead>