<?php require_once dirname(__FILE__).'/promoabrule-list.phtml' ?>
<?php require_once dirname(__FILE__).'/promoabrule-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/promoabrule-sectiongrid.phtml' ?>
<?php require_once dirname(__FILE__).'/promoabrule-sectionform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/promoabrule-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<?php } ?>
