<thead>
	<tr>
		<th mapping="promoab_id">promoab_id</th>
		<th mapping="promoabrule_dtstart">promoabrule_dtstart</th>
		<th mapping="brand_name">brand_name</th>
		<th mapping="promoab_descr">promoab_descr</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date Start</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Brand</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Descr</td>
	</tr>
</thead>