<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Size Tag</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row txt_merchsizetag_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_id" class="easyui-textbox" mapping="merchsizetag_id" uppercase="true" maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_name" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_name" class="easyui-textbox" mapping="merchsizetag_name" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama Report harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c01" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-01</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c01" class="easyui-textbox" mapping="merchsizetag_c01"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c02" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-02</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c02" class="easyui-textbox" mapping="merchsizetag_c02"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c03" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-03</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c03" class="easyui-textbox" mapping="merchsizetag_c03"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c04" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-04</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c04" class="easyui-textbox" mapping="merchsizetag_c04"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c05" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-05</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c05" class="easyui-textbox" mapping="merchsizetag_c05"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c06" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-06</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c06" class="easyui-textbox" mapping="merchsizetag_c06"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c07" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-07</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c07" class="easyui-textbox" mapping="merchsizetag_c07"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c08" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-08</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c08" class="easyui-textbox" mapping="merchsizetag_c08"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c09" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-09</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c09" class="easyui-textbox" mapping="merchsizetag_c09"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c10" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-10</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c10" class="easyui-textbox" mapping="merchsizetag_c10"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c11" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-11</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c11" class="easyui-textbox" mapping="merchsizetag_c11"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c12" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-12</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c12" class="easyui-textbox" mapping="merchsizetag_c12"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c13" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-13</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c13" class="easyui-textbox" mapping="merchsizetag_c13"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c14" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-14</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c14" class="easyui-textbox" mapping="merchsizetag_c14"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c15" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-15</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c15" class="easyui-textbox" mapping="merchsizetag_c15"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c16" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-16</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c16" class="easyui-textbox" mapping="merchsizetag_c16"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c17" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-17</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c17" class="easyui-textbox" mapping="merchsizetag_c17"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c18" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-18</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c18" class="easyui-textbox" mapping="merchsizetag_c18"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c19" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-19</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c19" class="easyui-textbox" mapping="merchsizetag_c19"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c20" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-20</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c20" class="easyui-textbox" mapping="merchsizetag_c20"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c21" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-21</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c21" class="easyui-textbox" mapping="merchsizetag_c21"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c22" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-22</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c22" class="easyui-textbox" mapping="merchsizetag_c22"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c23" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-23</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c23" class="easyui-textbox" mapping="merchsizetag_c23"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c24" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-24</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c24" class="easyui-textbox" mapping="merchsizetag_c24"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_merchsizetag_c25" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C-25</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsizetag_c25" class="easyui-textbox" mapping="merchsizetag_c25"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
			
			
			
			
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

