<div id="pnl_list">
	<div class="fgta-page-title">Daftar Size Tag</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<?php
		$customsearch = __DIR__.'/merchsizetag-list-customsearch.phtml'; 
		if (is_file($customsearch)) {
			include $customsearch;
		} else { ?>
		<!-- Simple Query -->
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
		<?php } ?>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<?php
				$customview = __DIR__.'/merchsizetag-list-customview.phtml'; 
				if (is_file($customview)) {
					include $customview;
				} else { ?>
				<tr>
					<th mapping="merchsizetag_id">merchsizetag_id</th>
					<th mapping="merchsizetag_name">merchsizetag_name</th>
					<th mapping="merchsizetag_c01">merchsizetag_c01</th>
					<th mapping="merchsizetag_c02">merchsizetag_c02</th>
					<th mapping="merchsizetag_c03">merchsizetag_c03</th>
					<th mapping="merchsizetag_c04">merchsizetag_c04</th>
					<th mapping="merchsizetag_c05">merchsizetag_c05</th>
					<th mapping="merchsizetag_c06">merchsizetag_c06</th>
					<th mapping="merchsizetag_c07">merchsizetag_c07</th>
					<th mapping="merchsizetag_c08">merchsizetag_c08</th>
					<th mapping="merchsizetag_c09">merchsizetag_c09</th>
					<th mapping="merchsizetag_c10">merchsizetag_c10</th>
					<th mapping="merchsizetag_c11">merchsizetag_c11</th>
					<th mapping="merchsizetag_c12">merchsizetag_c12</th>
					<th mapping="merchsizetag_c13">merchsizetag_c13</th>
					<th mapping="merchsizetag_c14">merchsizetag_c14</th>
					<th mapping="merchsizetag_c15">merchsizetag_c15</th>
					<th mapping="merchsizetag_c16">merchsizetag_c16</th>
					<th mapping="merchsizetag_c17">merchsizetag_c17</th>
					<th mapping="merchsizetag_c18">merchsizetag_c18</th>
					<th mapping="merchsizetag_c19">merchsizetag_c19</th>
					<th mapping="merchsizetag_c20">merchsizetag_c20</th>
					<th mapping="merchsizetag_c21">merchsizetag_c21</th>
					<th mapping="merchsizetag_c22">merchsizetag_c22</th>
					<th mapping="merchsizetag_c23">merchsizetag_c23</th>
					<th mapping="merchsizetag_c24">merchsizetag_c24</th>
					<th mapping="merchsizetag_c25">merchsizetag_c25</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-01</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-02</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-03</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-04</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-05</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-06</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-07</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-08</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-09</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-10</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-11</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-12</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-13</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-14</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-15</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-16</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-17</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-18</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-19</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-20</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-21</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-22</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-23</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-24</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">C-25</td>

				</tr>
				<?php } ?>
			</thead>
		</table>
	</div>



</div>