<div id="pnl_edititemsform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_edititemsform-caption">{{STATE_BEG}}Order Items{{STATE_END}}</div>
		<a id="pnl_edititemsform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_edititemsform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_edititemsform-form">

		<div class="form_row pnl_edititemsform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemsform-txt_merchorderinitem_id" class="easyui-textbox" mapping="merchorderinitem_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemsform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Item</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemsform-cbo_merchitem_id" class="easyui-combo" style="width: 400px" mapping="merchitem_id" display="itemstock_id" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Item harus diisi'"  validType="requiredcombo['pnl_edititemsform-cbo_merchitem_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemsform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Art</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemsform-txt_merchitem_art" class="easyui-textbox" mapping="merchitem_art"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemsform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Mat</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemsform-txt_merchitem_mat" class="easyui-textbox" mapping="merchitem_mat"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemsform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Col</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemsform-txt_merchitem_col" class="easyui-textbox" mapping="merchitem_col"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemsform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Size</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemsform-txt_merchitem_size" class="easyui-textbox" mapping="merchitem_size"  maxlength="10"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemsform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemsform-txt_merchitem_name" class="easyui-textbox" mapping="merchitem_name"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemsform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Qty</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemsform-txt_merchorderinitem_qty" class="easyui-numberbox" mapping="merchorderinitem_qty" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemsform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Price/pcs</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemsform-txt_merchorderinitem_valfrg" class="easyui-numberbox" mapping="merchorderinitem_valfrg" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemsform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Currency</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemsform-cbo_curr_id" class="easyui-combo" style="width: 400px" mapping="curr_id" display="curr_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Currency harus diisi', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_edititemsform-cbo_curr_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemsform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Rate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemsform-txt_merchorderinitem_valfrgrate" class="easyui-numberbox" mapping="merchorderinitem_valfrgrate" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemsform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Sub Total Frg</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemsform-txt_merchorderinitem_subvalfrg" class="easyui-numberbox" mapping="merchorderinitem_subvalfrg" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemsform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Sub Total IDR</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemsform-txt_merchorderinitem_subvalidr" class="easyui-numberbox" mapping="merchorderinitem_subvalidr" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , required: true, disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemsform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Order</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemsform-txt_merchorderin_id" class="easyui-textbox" mapping="merchorderin_id"  maxlength="30"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_edititemsform-autoadd" type="checkbox"><label for="pnl_edititemsform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_edititemsform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/merchorderin-itemsform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_edititemsform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_edititemsform-buttonbar-left">
			<a id="pnl_edititemsform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_edititemsform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_edititemsform-buttonbar-middle">
			<a id="pnl_edititemsform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_edititemsform-buttonbar-right">
			<a id="pnl_edititemsform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
