<div id="pnl_list">
	<div class="fgta-page-title">Daftar Item Stock</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<?php
		$customheadbutton = __DIR__.'/positem-list-customheadbutton.phtml'; 
		if (is_file($customheadbutton)) {
			include $customheadbutton;
		} else { ?>
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<?php } ?>

		<?php
		$customsearch = __DIR__.'/positem-list-customsearch.phtml'; 
		if (is_file($customsearch)) {
			include $customsearch;
		} else { ?>
		<!-- Simple Query -->
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
		<?php } ?>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<?php
			$customview = __DIR__.'/positem-list-customview.phtml'; 
			if (is_file($customview)) {
				include $customview;
			} else { ?>

			<thead>
				<tr>
					<th mapping="positemstock_id">positemstock_id</th>
					<th mapping="site_id">site_id</th>
					<th mapping="itemstock_id">itemstock_id</th>
					<th mapping="itemstock_code">itemstock_code</th>
					<th mapping="itemstock_name">itemstock_name</th>
					<th mapping="itemstock_isdisabled" type="checkbox">itemstock_isdisabled</th>
					<th mapping="itemstock_isupdating" type="checkbox">itemstock_isupdating</th>
					<th mapping="itemgroup_id">itemgroup_id</th>
					<th mapping="itemgroup_name">itemgroup_name</th>
					<th mapping="itemctg_id">itemctg_id</th>
					<th mapping="itemctg_name">itemctg_name</th>
					<th mapping="itemclass_id">itemclass_id</th>
					<th mapping="itemclass_name">itemclass_name</th>
					<th mapping="dept_id">dept_id</th>
					<th mapping="dept_name">dept_name</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Itemstock ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Uniq Code</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Nama Item</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Disabled</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Updating</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Item Group Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Category ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Category Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ItemClass ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ItemClass Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Dept ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Dept Name</td>

				</tr>
			</thead>

			<?php } ?>

		</table>
	</div>


	<?php
	$customfootbutton = __DIR__.'/positem-list-customfootbutton.phtml'; 
	if (is_file($customfootbutton)) {
		include $customfootbutton;
	} 
	?>	


</div>