<thead>
	<tr>
		<th mapping="merchitemctg_id">merchitemctg_id</th>
		<th mapping="merchitemctg_name">merchitemctg_name</th>
		<th mapping="itemclass_name">itemclass_name</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Category Name</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Class</td>
	</tr>
</thead>