<div id="pnl_detsize">
	<div class="fgta-page-title">Artikel Detil</div>


	<div class="fitem invcls_name"></div>
	<div style="display:flex; flex-direction: row; justify-content: space-between">
		<div>
			<div id="detsize_heinv_id" class="fitem heinv_id"></div>
			<div id="detsize_heinv_art" class="fitem heinv_art" style="font-weight:bold; font-size: 1.3em"></div>
			<div id="detsize_heinv_name" class="fitem heinv_name"></div>
			<div id="detsize_heinv_mat" class="fitem heinv_mat"></div>
			<div id="detsize_heinv_col" class="fitem heinv_col"></div>
		</div>
		<div style="text-align: right;">
			<div id="detsize_heinv_pricegross" class="fitem heinv_pricegross"></div>
			<div id="detsize_heinv_pricedisc" class="fitem heinv_pricedisc"></div>
			<div id="detsize_heinv_pricenett" class="fitem heinv_pricenett" style="font-weight:bold; font-size: 1.3em"></div>
		</div>
	</div>

	<div style="margin-top: 10px">
		<table id="pnl_detsize-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th mapping="HEINVITEM_ID">size</th>
					<th mapping="HEINV_SIZE">size</th>
					<th mapping="QTY">qty</th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Size</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Qty</td>
				</tr>
			</thead>
		</table>
	</div>

</div>