<div id="pnl_site">
	<div class="fgta-page-title">Artikel Location</div>

	<div class="fitem invcls_name"></div>
	<div style="display:flex; flex-direction: row; justify-content: space-between">
		<div>
			<div id="site_heinv_id" class="heinv_id"></div>
			<div id="site_heinv_art" class="heinv_art" style="font-weight:bold; font-size: 1.3em"></div>
			<div id="site_heinv_mat" class="heinv_mat"></div>
			<div id="site_heinv_col" class="heinv_col" ></div>
			<div id="site_heinv_size" class="heinv_size" style="font-weight:bold; font-size: 2em"></div>
		</div>
		<div style="text-align: right;">
			<div id="detsize_heinv_pricegross" class="heinv_pricegross"></div>
			<div id="detsize_heinv_pricedisc" class="heinv_pricedisc"></div>
			<div id="detsize_heinv_pricenett" class="heinv_pricenett" style="font-weight:bold; font-size: 1.3em"></div>
		</div>	
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_site-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th mapping="SITE_ID">size</th>
					<th mapping="QTY">qty</th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">SITE</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Qty</td>
				</tr>
			</thead>
		</table>
	</div>

</div>