<div id="pnl_list">
	<div class="fgta-page-title">Query Artikel</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">

		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%" value="50424393">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_search" class="easyui-linkbutton c8" style="width: 55px">Search</a>
			</div>
		</div>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th mapping="HEINV_ART">heinv_art</th>
					<th mapping="HEINV_MAT">heinv_mat</th>
					<th mapping="HEINV_COL">heinv_col</th>
					<th mapping="HEINV_ID">heinv_id</th>
					<th mapping="QTY">qty</th>
					<!-- <th mapping="HEINV_PRICE">heinv_price</th> -->
					<!-- <th mapping="HEINV_PRICEDISC">heinv_pricedisc</th> -->
					<!-- <th mapping="HEINV_PRICENETT">heinv_pricenett</th> -->
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Art</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Mat</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Col</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Id</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">Qty</td>
					<!-- <td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Price</td> -->
					<!-- <td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Disc</td> -->
					<!-- <td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Nett</td> -->
				</tr>
			</thead>
		</table>
	</div>

</div>