<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit POS Paym Type</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_paytype_id" class="easyui-textbox" mapping="paytype_id" uppercase="true" maxlength="14" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Type Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_paytype_name" class="easyui-textbox" mapping="paytype_name" uppercase="true" maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col">Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_paytype_iscash" class="easyui-checkbox c1" mapping="paytype_iscash" data-options="label: 'Cash', labelPosition: 'after', checked: false , disabled: false">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_paytype_isvoucher" class="easyui-checkbox c1" mapping="paytype_isvoucher" data-options="label: 'Voucher', labelPosition: 'after', checked: false , disabled: false">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_paytype_isedc" class="easyui-checkbox c1" mapping="paytype_isedc" data-options="label: 'EDC', labelPosition: 'after', checked: false , disabled: false">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_paytype_istransfer" class="easyui-checkbox c1" mapping="paytype_istransfer" data-options="label: 'Transfer', labelPosition: 'after', checked: false , disabled: false">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_paytype_isonline" class="easyui-checkbox c1" mapping="paytype_isonline" data-options="label: 'Online Platform', labelPosition: 'after', checked: false , disabled: false">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name InputType</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_paytype_nameinputtype" class="easyui-textbox" mapping="paytype_nameinputtype" lowercase="true" maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Card InputType</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_paytype_cardinputtype" class="easyui-textbox" mapping="paytype_cardinputtype" lowercase="true" maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Appr InputType</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_paytype_apprinputtype" class="easyui-textbox" mapping="paytype_apprinputtype" lowercase="true" maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/pospaytype-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			
			
			
			
			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

