<?php require_once dirname(__FILE__).'/mercharticle-list.phtml' ?>
<?php require_once dirname(__FILE__).'/mercharticle-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/mercharticle-itemgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/mercharticle-itemform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/mercharticle-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<?php } ?>
