<thead>
	<tr>
		<th mapping="merchorderout_id">merchorderout_id</th>
		<th mapping="merchorderout_descr">merchorderout_descr</th>
		<th mapping="orderout_qty" style="text-align: right"  formatter="row_format_number">orderout_qty</th>
		<th mapping="orderout_totalvaluefrg" style="text-align: right"  formatter="row_format_number">orderout_totalvaluefrg</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Descr</td>
		<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Qty</td>
		<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Value</td>
	</tr>
</thead>