<!-- ini blank phtml -->
<div id="pnl_editpreview" style="position: absolute; top: 5px; bottom: 5px; right: 5px; left: 5px; display: flex; flex-direction: column;">
	<div id="pnl_editpreview-pnl_head" style="display: flex; justify-content: space-between; margin-top: 5px ">
		Preview
		<a href="javascript:void(0)" id="pnl_editpreview-btn_print" class="easyui-linkbutton c8" style="width: 45px">Print</a>
	</div>
	<div id="rpt_container" style="margin-top: 10px; border: 1px solid #000; flex: 1">
		<iframe id="pnl_editpreview-obj_report" style="border: 0px; width:100%; height:100%;">
		</iframe>
	</div>
</div>	
