<!-- ini blank phtml -->
<div id="pnl_editbill">
	<div class="fgta-page-title">Bill to TFI</div>


	<div id="pnl_editbill-shipmentdata">loading...</div>
	<a id="pnl_editbill-btn_calculate" class="easyui-linkbutton">Calculate</a>
	<br><br><br>
	<div id="pnl_editbill-currentcalculation">loading...</div>


	<a id="pnl_editbill-btn_execute" class="easyui-linkbutton">Execute</a>

	<br><br><br>
	<div id="pnl_editbill-invoice">loading...</div>

	<br><br><br>
	<div id="pnl_editbill-salesorder">loading...</div>

	<br><br><br>
	<div id="pnl_editbill-delivery">loading...</div>

	<br><br><br>
	<div id="pnl_editbill-salesjurnal">loading...</div>

</div>	
