<tfoot>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="rowcheck" style="width: 30px; border-top: 1px solid #999; text-align: center">&nbsp;</td>
		<td class="" style="border-top: 1px solid #999; font-weight: bold">TOTAL</td>
		<td id="pnl_editbudgetgrid-totalvalue" class="" style="width: 100px; text-align: right; border-top: 1px solid #999; font-weight: bold"></td>
	</tr>
</tfoot>