<div id="pnl_editorderoutform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editorderoutform-caption">{{STATE_BEG}}Order{{STATE_END}}</div>
		<a id="pnl_editorderoutform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editorderoutform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editorderoutform-form">

		<div class="form_row pnl_editorderoutform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editorderoutform-txt_merchshiporderout_id" class="easyui-textbox" mapping="merchshiporderout_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editorderoutform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Order</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editorderoutform-cbo_merchorderout_id" class="easyui-combo" style="width: 400px" mapping="merchorderout_id" display="merchorderout_descr" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Order harus diisi'"  validType="requiredcombo['pnl_editorderoutform-cbo_merchorderout_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editorderoutform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Season</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editorderoutform-cbo_merchsea_id" class="easyui-combo" style="width: 400px" mapping="merchsea_id" display="merchsea_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Season harus diisi', disabled: true"  validType="requiredcombo['pnl_editorderoutform-cbo_merchsea_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editorderoutform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Currency</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editorderoutform-cbo_curr_id" class="easyui-combo" style="width: 400px" mapping="curr_id" display="curr_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Currency harus diisi', prompt: '-- PILIH --', disabled: true"  validType="requiredcombo['pnl_editorderoutform-cbo_curr_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editorderoutform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Qty</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editorderoutform-txt_orderout_qty" class="easyui-numberbox" mapping="orderout_qty" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editorderoutform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Value Frg</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editorderoutform-txt_orderout_valuefrg" class="easyui-numberbox" mapping="orderout_valuefrg" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editorderoutform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Value IDR</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editorderoutform-txt_orderout_valueidr" class="easyui-numberbox" mapping="orderout_valueidr" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editorderoutform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Shipment</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editorderoutform-txt_merchship_id" class="easyui-textbox" mapping="merchship_id"  maxlength="30"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editorderoutform-autoadd" type="checkbox"><label for="pnl_editorderoutform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editorderoutform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/merchship-orderoutform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editorderoutform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editorderoutform-buttonbar-left">
			<a id="pnl_editorderoutform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editorderoutform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editorderoutform-buttonbar-middle">
			<a id="pnl_editorderoutform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editorderoutform-buttonbar-right">
			<a id="pnl_editorderoutform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
