<thead>
	<tr>
		<th type="check">chk</th>					
		<th mapping="merchshipbudget_descr">merchshipbudget_descr</th>
		<th mapping="merchshipbudget_idr" style="text-align: right" formatter="row_format_number">merchshipbudget_idr</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head rowcheck" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">&nbsp;</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Descr</td>
		<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Value (<?=__LOCAL_CURR?>)</td>
	</tr>
</thead>