<div class="container-full">

	<div id="pnl_login" class="loginframe hidden z-depth-4 grey lighten-4">

		<div class='row'>
			<div class='input-field col s12'>
				<h5>Login</h5>
			</div>
		</div>
		<div class='row'>
			<div class='input-field col s12'>
				<label for="obj_txt_username">Username</label>
				<input id="obj_txt_username" type="text" class="validate">
			</div>
		</div>

		<div class='row'>
			<div class='input-field col s12'>
				<label for='password'>Password</label>
				<input id='obj_txt_password' type='password'  class='validate'>
			</div>
		</div>
		<div class='row'>
			<div class='col s12'>
				<label for="obj_chk_remember">
					<input type="checkbox" id="obj_chk_remember">
					<span>Remember me</span>
				</label>
			</div>
		</div>

		<div class='row'>
			<button id="btn_login" class='col s12 btn btn-large waves-effect'>Login</button>
		</div>
		<div id="pnl_setting" style="text-align: center; display: none" >
			<a id="btn_setting" href="javascript:void(0)">Setting</a>
		</div>

	</div>	

</div>