<script>
	window.global.crmevent_id = '<?=$this->crmevent_id?>';
</script>	

<div id="pnl_display" class="fullcontent page-panel posmain-container">
	<a id="btn_fullscreen" class="waves-effect waves-light btn">Full Screen</a>	
	<a id="btn_update" class="waves-effect waves-light btn">Update</a>	
	<a id="btn_close" class="waves-effect waves-light btn">Close</a>	
	<div id="pnl_display-screen" class="screendisplay hidden">
		

		<div class="row">
			<div class="input-field col s12 display-header">
				<div class="header-title">Raker 2023</div>
				<div class="header-subtitle">&nbsp;</div>				
			</div>
		</div>
		<div class="row">
			<div class="col s4 display-column">
				<img src="index.php/public/assets/logo_tfb.png">
			</div>	
			<div class="col s4 display-column">
			<img src="index.php/public/assets/logo_metro.png">
			</div>	
			<div class="col s4 display-column">
				<img src="index.php/public/assets/logo_tfi.png">
			</div>	
		</div>
		<div class="row">
			<div class="col s4 display-cellcontainer">
				<div id="pnl_display-chart-01" class="display-chart"></div>
			</div>
			<div class="col s4 display-cellcontainer">
				<div id="pnl_display-chart-02" class="display-chart"></div>
			</div>
			<div class="col s4 display-cellcontainer">
				<div id="pnl_display-chart-03" class="display-chart"></div>
			</div>
		</div>
		<div class="row">
			<div class="col s12 display-column">
				<div id="pnl_display-marquebanner" class="marquee">
					<div class="marquee__content display-banner-text">
						masih ditunggu kehadirannya ...
					</div>
					<ul aria-hidden="true" class="marquee__content display-banner-text" style="margin-top: 0px">
						masih ditunggu kehadirannya ...
					</ul>
				</div>
			</div>
		</div>
		<div class="row">
			<div id="pnl_display-group1" class="col s4 display-column display-listitem display-listitem-tran">
			</div>	
			<div id="pnl_display-group2" class="col s4 display-column display-listitem display-listitem-tran">
			</div>	
			<div id="pnl_display-group3" class="col s4 display-column display-listitem display-listitem-tran">
			</div>	
		</div>
	</div>
</div>