<thead>
	<tr>
		<th mapping="merchsea_id">merchsea_id</th>
		<th mapping="merchsea_name">merchsea_name</th>
		<th mapping="merchsea_year" style="text-align: right"  formatter="row_format_number">merchsea_year</th>
		<th mapping="merchsea_isdisabled" type="checkbox">merchsea_isdisabled</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Season</td>
		<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Year</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Disabled</td>
	</tr>
</thead>