<div id="pnl_edititemform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_edititemform-caption">{{STATE_BEG}}Items{{STATE_END}}</div>
		<a id="pnl_edititemform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_edititemform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_edititemform-form">

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchregitem_id" class="easyui-textbox" mapping="merchregitem_id"  maxlength="32"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">RefCode</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_refcode" class="easyui-textbox" mapping="merchitem_refcode"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">RefItem</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_refitem" class="easyui-textbox" mapping="merchitem_refitem"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Barcode</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_barcode" class="easyui-textbox" mapping="merchitem_barcode"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Art</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_art" class="easyui-textbox" mapping="merchitem_art"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Mat</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_mat" class="easyui-textbox" mapping="merchitem_mat"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Col</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_col" class="easyui-textbox" mapping="merchitem_col"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Size</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_size" class="easyui-textbox" mapping="merchitem_size"  maxlength="10"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Combo</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_combo" class="easyui-textbox" mapping="merchitem_combo"  maxlength="103"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_name" class="easyui-textbox" mapping="merchitem_name"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_descr" class="easyui-textbox" mapping="merchitem_descr"  maxlength="2500"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Colnum</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_colnum" class="easyui-textbox" mapping="merchitem_colnum"  maxlength="3"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-chk_merchitem_isdisabled" class="easyui-checkbox c1" mapping="merchitem_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">pcp Line</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_pcpline" class="easyui-textbox" mapping="merchitem_pcpline"  maxlength="90"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">pcp group</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_pcpgroup" class="easyui-textbox" mapping="merchitem_pcpgroup"  maxlength="90"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">pcp category</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_pcpcategory" class="easyui-textbox" mapping="merchitem_pcpcategory"  maxlength="90"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">color code</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_colorcode" class="easyui-textbox" mapping="merchitem_colorcode"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">color descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_colordescr" class="easyui-textbox" mapping="merchitem_colordescr"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Gender</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_gender" class="easyui-textbox" mapping="merchitem_gender"  maxlength="1"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Fit</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_fit" class="easyui-textbox" mapping="merchitem_fit"  maxlength="10"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">HSCode (ship)</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_hscodeship" class="easyui-textbox" mapping="merchitem_hscodeship"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">HSCode (ina)</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_hscodeina" class="easyui-textbox" mapping="merchitem_hscodeina"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">GType</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_gtype" class="easyui-textbox" mapping="merchitem_gtype"  maxlength="5"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">label name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_labelname" class="easyui-textbox" mapping="merchitem_labelname"  maxlength="90"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">label product</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_labelproduct" class="easyui-textbox" mapping="merchitem_labelproduct"  maxlength="90"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">label bahan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_bahan" class="easyui-textbox" mapping="merchitem_bahan"  maxlength="150"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">label pemeliharaan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_pemeliharaan" class="easyui-textbox" mapping="merchitem_pemeliharaan"  maxlength="150"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">label logo</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_logo" class="easyui-textbox" mapping="merchitem_logo"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">label dibuatdi</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_dibuatdi" class="easyui-textbox" mapping="merchitem_dibuatdi"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Width</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_width" class="easyui-numberbox" mapping="merchitem_width" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Length</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_length" class="easyui-numberbox" mapping="merchitem_length" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Height</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_height" class="easyui-numberbox" mapping="merchitem_height" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Weight</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_weight" class="easyui-numberbox" mapping="merchitem_weight" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">fob</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_fob" class="easyui-numberbox" mapping="merchitem_fob" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">init Qty</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_initqty" class="easyui-numberbox" mapping="merchitem_initqty" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Category</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitemctg_id" class="easyui-textbox" mapping="merchitemctg_id"  maxlength="30"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Category harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ItemId</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchitem_id" class="easyui-textbox" mapping="merchitem_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ArticleId</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_mercharticle_id" class="easyui-textbox" mapping="mercharticle_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Unit</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_unit_id" class="easyui-textbox" mapping="unit_id"  maxlength="10"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_dept_id" class="easyui-textbox" mapping="dept_id"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Brand</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_brand_id" class="easyui-textbox" mapping="brand_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ArtMatPair</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_mercharticle_paircode" class="easyui-textbox" mapping="mercharticle_paircode"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edititemform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Reg</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edititemform-txt_merchreg_id" class="easyui-textbox" mapping="merchreg_id"  maxlength="30"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_edititemform-autoadd" type="checkbox"><label for="pnl_edititemform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_edititemform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/merchreg-itemform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_edititemform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_edititemform-buttonbar-left">
			<a id="pnl_edititemform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_edititemform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_edititemform-buttonbar-middle">
			<a id="pnl_edititemform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_edititemform-buttonbar-right">
			<a id="pnl_edititemform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
