<div id="pnl_reset">
	<div class="fgta-page-title">Reset Database</div>

	<div>
		<p>
			Anda akan me-reset database opname.<br>
			Seluruh data item yang telah terscan dan belum dikirim ke server akan <b>terhapus</b>.
		</p>
		<p>
			<span style="color: red"><b>Peringatan!!</b></span><br> 
			Proses ini <b>tidak bisa di UNDO</b>.
		</p>
	</div>


	<div>
		<div>Masukkan kode '<span id="pnl_reset-obj_txt_randomcode" style="font-weight: bold"></span>' untuk menghapus data:</div>
		<input id="pnl_reset-obj_txt_removecode" class="easyui-textbox c5" style="width: 50px">
		<a id="pnl_reset-btn_removedb" class="easyui-linkbutton c5">Hapus Data</a>
	</div>
</div>