<div id="pnl_form">
	<div class="fgta-page-title">Form</div>

	<!-- TODO: Pilih toko sesuai login -->
	<div id="pnl_form-board">


		<div>
			<div>Site</div>
			<div>
				<input id="pnl_form-obj_txt_site" class="easyui-textbox" data-options="prompt:'kode-site'">
				<a id="pnl_form-btn_liststore" class="easyui-linkbutton">List Toko</a>
			</div>	
		</div>
		<div>
			<div>Tanggal</div>
			<div>
				<input id="pnl_form-obj_dt_opnamedate" class="easyui-datebox">
			</div>
		</div>
		<div>
			<div>Keterangan</div>
			<div>
				<input id="pnl_form-obj_txt_descr" class="easyui-textbox">
			</div>
		</div>

		<div>
			<a id="pnl_form-btn_downloadstock" class="easyui-linkbutton">Download Stock<a>
		</div>

	</div>




</div>