<?php require_once dirname(__FILE__).'/proprog-list.phtml' ?>
<?php require_once dirname(__FILE__).'/proprog-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/proprog-groupagrid.phtml' ?>
<?php require_once dirname(__FILE__).'/proprog-groupaform.phtml' ?>
<?php require_once dirname(__FILE__).'/proprog-groupbgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/proprog-groupbform.phtml' ?>
<?php require_once dirname(__FILE__).'/proprog-sitegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/proprog-siteform.phtml' ?>
<?php require_once dirname(__FILE__).'/proprog-pospaymgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/proprog-pospaymform.phtml' ?>
<?php require_once dirname(__FILE__).'/proprog-approvalgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/proprog-approvalform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/proprog-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<div id="pnl_edit_record_custom" style="display: none">
	<div class="form_row">
		<div class="form_label_col">Commit By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Commit Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitdate"></span>
		</div>
	</div> 

	<div class="form_row" style="margin-top: 30px;">
		<div class="form_label_col">Approve By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-approveby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Approve Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-approvedate"></span>
		</div>
	</div>	

	<div class="form_row" style="margin-top: 30px;">
		<div class="form_label_col">Decline By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-declineby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Decline Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-declinedate"></span>
		</div>
	</div>	

</div>	
			
<?php } ?>
