<thead>
	<tr>
		<th mapping="store_code" style="text-align: center">store_code</th>
		<th mapping="posterminal_status">posterminal_status</th>
		<th mapping="site_name">site_name</th>
		<th mapping="posterminal_code" style="text-align: center">posterminal_code</th>
		<th mapping="posterminal_setupcode" style="display: none">posterminal_setupcode</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center;">Store Code</td>
		<td class="fgtable-head" style="width: 38px; border-bottom: 1px solid #000000">&nbsp;</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Site</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center;">Terminal Code</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; display: none">Setup Code</td>
	</tr>
</thead>