<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit POS Terminal</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_posterminal_id" class="easyui-textbox" mapping="posterminal_id"  maxlength="14" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Site</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_site_id" class="easyui-combo" style="width: 400px" mapping="site_id" display="site_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Site harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_site_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Store Code</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_store_code" class="easyui-textbox" mapping="store_code"  maxlength="3" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Terminal Code</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_posterminal_code" class="easyui-textbox" mapping="posterminal_code"  maxlength="2" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">License</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_posterminal_license" class="easyui-textbox" mapping="posterminal_license"  maxlength="64" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_posterminal_licenseunlimited" class="easyui-checkbox c1" mapping="posterminal_licenseunlimited" data-options="label: 'Unlimitted', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Expired Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_posterminal_expireddate" class="easyui-datebox" style="width: 400px" mapping="posterminal_expireddate" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Setup Code</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_posterminal_setupcode" class="easyui-textbox" mapping="posterminal_setupcode"  maxlength="6" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>
		<div id="pnl_edit-setupcode" class="setupinfo setupinfo-hidden"></div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_posterminal_islock" class="easyui-checkbox c1" mapping="posterminal_islock" data-options="label: 'Lock', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/posterminal-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			
			
			
							<a id="pnl_edit-btn_setup" href="javascript:void(0)" class="easyui-linkbutton c8" style="width: 80px; margin-left:10px; margin-bottom: 10px;" data-options="plain:true">Gen S.C</a>
				<a id="pnl_edit-btn_lock" href="javascript:void(0)" class="easyui-linkbutton c8" style="width: 80px; margin-left:10px; margin-bottom: 10px;" data-options="plain:true">Lock</a>
				<a id="pnl_edit-btn_unlock" href="javascript:void(0)" class="easyui-linkbutton c8" style="width: 80px; margin-left:10px; margin-bottom: 10px;" data-options="plain:true">UnLock</a>

			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

