<thead>
	<tr>
		<th mapping="merchitemgro_id">merchitemgro_id</th>
		<th mapping="merchitemgro_name">merchitemgro_name</th>
		<th mapping="brand_name">brand_id</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Group Name</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Brand</td>
	</tr>
</thead>