<?php require_once dirname(__FILE__).'/merchitemgro-list.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitemgro-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitemgro-picturegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitemgro-pictureform.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitemgro-propgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitemgro-propform.phtml' ?>



