<div id="pnl_viewtx">

	<div class="fgta-page-title"  style="margin-bottom: 0px">
		<div>SLXXXXX</div>
	</div>




	<div style="margin-top: 10px">
		<table id="pnl_viewtx-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th mapping="BON_ID">site_id</th>
					<th mapping="BON_DATE">bon_date</th>
					<th mapping="QTY">qty</th>
					<th mapping="GROSS">gross</th>
					<th mapping="NETT">nett</th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">BON</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Date</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">Qty</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">Gross</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">Nett</td>
				</tr>
			</thead>
			<tfoot>
				<tr style="background-color: #cccccc; height: 30px;">
					<td class="fgtable-head-alt1" colspan="2">TOTAL</td>
					<td class="fgtable-head-alt1" style="width: 100px; border-bottom: 1px solid #000000; text-align: right"><div id="pnl_listtx-total_qty" style="text-align: right">0</div></td>
					<td class="fgtable-head-alt1" style="width: 100px; border-bottom: 1px solid #000000; text-align: right"><div id="pnl_listtx-total_gross" style="text-align: right">0</div></td>
					<td class="fgtable-head-alt1" style="width: 100px; border-bottom: 1px solid #000000; text-align: right"><div id="pnl_listtx-total_nett" style="text-align: right">0</div></td>
				</tr>
			</tfoot>			
		</table>
	</div>	
</div>	