<div id="pnl_listcity">

	<!-- <div class="fgta-page-title">Sales By City</div>
 -->

	<div class="mfcontainer">
		<div class="mfrow">
			<div class="mffield">
				<div class="mflabel">Start</div>
				<div class="mfcomp"><input id="pnl_listcity-obj_date_start" class="easyui-datebox" style="width:100%" data-options="editable: false"></div>
			</div>

			<div class="mffield">
				<div class="mflabel">End</div>
				<div class="mfcomp"><input id="pnl_listcity-obj_date_end" class="easyui-datebox" style="width:100%" data-options="editable: false"></div>
			</div>
			
			<div class="mffield">
				<div class="mflabel"></div>
				<div class="mfcomp">
					<a href="javascript:void(0)" id="pnl_listcity-btn_load" class="easyui-linkbutton c8" style="width: 55px">Load</a>
				</div>
			</div>
		</div>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_listcity-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th mapping="CITY_ID">city_id</th>
					<th mapping="TX">tx</th>
					<th mapping="QTY">qty</th>
					<th mapping="GROSS">gross</th>
					<th mapping="NETT">nett</th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">CITY</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">Tx</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">Qty</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">Gross</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">Nett</td>
				</tr>
			</thead>
			<tfoot>
				<tr style="background-color: #cccccc; height: 30px;">
					<td class="fgtable-head-alt1" >TOTAL</td>
					<td class="fgtable-head-alt1" style="width: 100px; border-bottom: 1px solid #000000; text-align: right"><div id="pnl_listcity-total_tx" style="text-align: right">0</div></td>
					<td class="fgtable-head-alt1" style="width: 100px; border-bottom: 1px solid #000000; text-align: right"><div id="pnl_listcity-total_qty" style="text-align: right">0</div></td>
					<td class="fgtable-head-alt1" style="width: 100px; border-bottom: 1px solid #000000; text-align: right"><div id="pnl_listcity-total_gross" style="text-align: right">0</div></td>
					<td class="fgtable-head-alt1" style="width: 100px; border-bottom: 1px solid #000000; text-align: right"><div id="pnl_listcity-total_nett" style="text-align: right">0</div></td>
				</tr>
			</tfoot>
		</table>
	</div>

</div>