

<!-- START: Query Box -->
<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
	<div class="list-search-param" style="width: 280px">
		<div class="list-search-item" style="width: 50px; align-self:center; text-align: right">Unit</div>
		<div class="list-search-item" style="width: 200px">
			<input id="pnl_list-cbo_search_unit" class="easyui-combo" style="width: 100%" data-options="required: true">
		</div>
	</div>

	<div class="list-search-param" style="width: 180px">
		<div class="list-search-item" style="width: 50px;align-self:center; text-align: right">Cari</div>
		<div class="list-search-item" style="width: 100px">
			<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
		</div>
	</div>
	
	<div class="list-search-item" style="width: 45px">
		<a href="javascript:void(0)" id="pnl_list-btn_filter" class="easyui-linkbutton" 
			style="width: 20px; background: url('../../../../../images/icon-filter.svg'); background-repeat: no-repeat" data-options="plain:true">
		</a>
		<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
	</div>

</div>
<!-- END: Query Box -->