<div id="pnl_edititemsgrid">
	<div class="fgta-page-title">Daftar Items</div>
	<div id="pnl_edititemsgrid-title" class="fgta-page-subtitle">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_edititemsgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_edititemsgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_edititemsgrid-btn_load" class="easyui-linkbutton c8 fgta-button-listload" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->


	<?php
	$customheadpanel = __DIR__.'/merchrv-itemsgrid-customheadpanel.phtml';
	if (is_file($customheadpanel)) {
		include $customheadpanel;
	} 
	?>

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_edititemsgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<?php
			$customview = __DIR__.'/merchrv-itemsgrid-customview.phtml'; 
			if (is_file($customview)) {
				include $customview;
			} else { ?>
			<thead>

				<tr>
<th type="check">chk</th>					
					<th mapping="merchrvitem_id">merchrvitem_id</th>
					<th mapping="itemstock_id">itemstock_id</th>
					<th mapping="merchitem_combo">merchitem_combo</th>
					<th mapping="merchitem_name">merchitem_name</th>
					<th mapping="merchrvitem_valuepo" style="text-align: right" formatter="row_format_number">merchrvitem_valuepo</th>
					<th mapping="merchrvitem_value" style="text-align: right" formatter="row_format_number">merchrvitem_value</th>
					<th mapping="merchrvitem_qtyinit" style="text-align: right" formatter="row_format_number">merchrvitem_qtyinit</th>
					<th mapping="merchrvitem_qty" style="text-align: right" formatter="row_format_number">merchrvitem_qty</th>
					<th mapping="merchrvitem_rate" style="text-align: right" formatter="row_format_number">merchrvitem_rate</th>
					<th mapping="merchrvitem_subtotalvaluefrg" style="text-align: right" formatter="row_format_number">merchrvitem_subtotalvaluefrg</th>
					<th mapping="merchrvitem_actualvaluefrg" style="text-align: right" formatter="row_format_number">merchrvitem_actualvaluefrg</th>
					<th mapping="merchrvitem_actualrate" style="text-align: right" formatter="row_format_number">merchrvitem_actualrate</th>

					<th mapping=""></th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
<td class="fgtable-head rowcheck" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Item</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Combo</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Name</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Value from PO</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Value</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Qty PL</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Qty Actual</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Rate</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Subtotal</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Actual Value</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Actual Rate</td>

					<td class="fgtable-head" style="border-bottom: 1px solid #000000; text-align: center">&nbsp;</td>
				</tr>
			</thead>
			<?php } ?>
			
			<?php
			$tablefooter = __DIR__.'/merchrv-itemsgrid-tablefooter.phtml';
			if (is_file($tablefooter)) {
				include $tablefooter;
			} 
			?>
			
		</table>
	</div>



	<div class="pnl_edititemsgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_edititemsgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8 fgta-button-rowdel">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_edititemsgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8 fgta-button-rowadd">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>



	<?php
	$customfootpanel = __DIR__.'/merchrv-itemsgrid-customfootpanel.phtml';
	if (is_file($customfootpanel)) {
		include $customfootpanel;
	} 
	?>

</div>	
