<?php require_once dirname(__FILE__).'/merchctg-list.phtml' ?>
<?php require_once dirname(__FILE__).'/merchctg-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/merchctg-refgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/merchctg-refform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/merchctg-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<?php } ?>
