<div id="obj_navbar" class="navbar-fixed">
	<nav>
		<div class="nav-wrapper pos-header"> 
			<div class="pos-title-username-container">
				<i class="material-icons">account_circle</i>
				<div id="obj_txt_container-username">username</div>
			</div>
			<span class="brand-logo center">
				<div id="obj_txt_container-date" class="pos-title-date"></div>
				<div class="pos-title-site-container">
					<i class="material-icons">location_on</i>
					<div id="obj_txt_container-site">site</div>
				</div> 
			</span>
			<ul class="right">
				<li><a id="btn_MenuOpen" href="javascript:void(0)"><i class="material-icons pos-navbar-item">apps</i></a></li>
			</ul>
		</div>
	</nav>
</div>	

<ul id="obj_SideNavMenu" class="sidenav posmenupanel">
	<li><a class="subheader">Menu</a></li>
	<li><a class="waves-effect container-menu-button" data-module-id="retail/pos/posmain">Sale</a></li>
	<!-- <li><a class="waves-effect container-menu-button" data-module-id="retail/pos/allotopup">Allo Top Up</a></li> -->
	<li><a class="waves-effect container-menu-button" data-module-id="retail/pos/guestbook">Guest Book</a></li>
	<li><a class="waves-effect container-menu-button" data-module-id="retail/pos/afeattest">Fetaure Test</a></li>
	<li><a class="waves-effect container-menu-button" data-module-id="action" data-action="reload">Reload</a></li>
	<li><a class="waves-effect container-menu-button" data-module-id="action" data-action="logout">Logout</a></li>
</ul>


<!-- MAIN CONTAINER APPS BEGIN -->
<div id="obj_framescontainer" class="framescontainer">
	<div id="obj_framescontainer-loading" class="fullcontent">Loading Module ...</div>
</div>
<!-- MAIN CONTAINER APPS END -->