feature test


<div style="margin-top: 20px; border: 1px solid #ccc">
	<div>Coba Print Text</div>
	<div>
		<textarea id="printContent">
coba cetak text baris 1
coba cetak text baris 2
coba cetak text baris 3
coba cetak text baris 4
		</textarea>
	</div>	
	<div>	
		<button id="btn_printtest-text">Print</button>
	</div>
</div>


<div style="margin-top: 20px; border: 1px solid #ccc">
	<div>Coba Print Image</div>
	<div>
		<img id="img_logo" src="index.php/asset/retail/pos/afeattest/image/logo-mblock.bmp">
	</div>
	<div>
		<button id="btn_printtest-image">Print</button>
	</div>

</div>


<div style="margin-top: 50px; border: 1px solid #ccc">
	<div>Coba Print via bluetooth printer</div>
	<div>
		<button id="btn_printtestblue-text">Print</button>
	</div>

</div>

