<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_edit-caption">{{STATE_BEG}}Syncronize Document{{STATE_END}}</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsync_id" class="easyui-textbox" mapping="merchsync_id" uppercase="true" maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'ID harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Document</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsync_doc" class="easyui-textbox" mapping="merchsync_doc"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsync_type" class="easyui-textbox" mapping="merchsync_type"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_merchsync_isprocessing" class="easyui-checkbox c1" mapping="merchsync_isprocessing" data-options="label: 'Processing', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">TimeOut</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsync_timeout" class="easyui-textbox" mapping="merchsync_timeout"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Batch</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsync_batch" class="easyui-textbox" mapping="merchsync_batch"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_merchsync_isfail" class="easyui-checkbox c1" mapping="merchsync_isfail" data-options="label: 'Fail', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_merchsync_iscompleted" class="easyui-checkbox c1" mapping="merchsync_iscompleted" data-options="label: 'Completed', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Result</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchsync_result" class="easyui-textbox" mapping="merchsync_result"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/merchsync-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			
			
			
			
			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5 fgta-button-delete" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

