<div id="pnl_gro">
	<div class="fgta-page-title">Report by Group</div>
	<div id="pnl_search-board">
		<table id="pnl_gro-dgv_list" class="easyui-datagrid" data-options="singleSelect:true" >
			<thead>
				<th data-options="field:'gro_id',width:100">Group</th>
				<th data-options="field:'gro_name',width:100">Group</th>
				<th data-options="field:'qty',width:100">Inv</th>
				<th data-options="field:'qtyscanned',width:100">Scan</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>	
</div>

