<?php require_once dirname(__FILE__).'/opnamerpt1-search.phtml' ?>
<?php require_once dirname(__FILE__).'/opnamerpt1-gro.phtml' ?>
<?php require_once dirname(__FILE__).'/opnamerpt1-ctg.phtml' ?>
<?php require_once dirname(__FILE__).'/opnamerpt1-art.phtml' ?>
<?php require_once dirname(__FILE__).'/opnamerpt1-artd.phtml' ?>

<!--
test
<p>
* by group -> drill down<br>
* by category -> drill down<br>
* by article -> drill down<br>
* search by article <br>
</p>
//-->
<div style="margin-top: 5px">
<a id="btn_searchbyart" class="easyui-linkbutton" plain="true"><u>Search by Article</u></a> | 
<a id="btn_summary" class="easyui-linkbutton" plain="true"><u>Summary</u></a>
</div>