<div id="pnl_ctg">
	<div class="fgta-page-title">Report by Category</div>
	<div id="pnl_search-board">
		<table id="pnl_ctg-dgv_list" class="easyui-datagrid" data-options="singleSelect:true" >
			<thead>
				<th data-options="field:'gro_id',width:100">Group</th>
				<th data-options="field:'gro_name',width:100">Group</th>
				<th data-options="field:'ctg_id',width:100">Category</th>
				<th data-options="field:'ctg_name',width:100">Category</th>
				<th data-options="field:'qty',width:100">Inv</th>
				<th data-options="field:'qtyscanned',width:100">Scan</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>

</div>

