<div id="pnl_search">
	<div class="fgta-page-title">Search Articles</div>
	<div id="pnl_search-board">
	
		<div id="pnl_search-searchbar" style="display: flex; margin-bottom: 20px">
			<div >
				<input id="pnl_search-obj_txt_input" class="easyui-textbox" data-options="prompt:'input kode artikel',buttonText:'ok'">
			</div>
			<div style="width: 70px; padding-left: 5px">
			</div>
		</div>

		<table id="pnl_search-dgv_list" class="easyui-datagrid" data-options="singleSelect:true, remoteSort:false, multiSort:true" >
			<thead>
				<th data-options="field:'art',width:100">Art</th>
				<th data-options="field:'mat',width:100, sortable:true">Mat</th>
				<th data-options="field:'col',width:100, sortable:true">Col</th>
				<th data-options="field:'size',width:100, sortable:true">Size</th>
				<th data-options="field:'qty',width:100">Inv</th>
				<th data-options="field:'qtyscanned',width:100">Scan</th>
			</thead>
			<tbody>
			</tbody>
		</table>

	</div>
</div>

