<div id="pnl_art">
	<div class="fgta-page-title">Report by Article</div>
	<div id="pnl_search-board">
		<table id="pnl_art-dgv_list" class="easyui-datagrid" data-options="singleSelect:true" >
			<thead>
				<th data-options="field:'art',width:100">Art</th>
				<th data-options="field:'mat',width:100">Mat</th>
				<th data-options="field:'col',width:100">Col</th>
				<th data-options="field:'size',width:100">Size</th>
				<th data-options="field:'qty',width:100">Inv</th>
				<th data-options="field:'qtyscanned',width:100">Scan</th>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>

</div>

