<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Promo AB Model</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_promoabmodel_id" class="easyui-textbox" mapping="promoabmodel_id"  maxlength="14" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_promoabmodel_descr" class="easyui-textbox" mapping="promoabmodel_descr"  maxlength="255" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Descr harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Rule</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_promoabrule_id" class="easyui-combo" style="width: 400px" mapping="promoabrule_id" display="promoabrule_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Rule harus diisi'"   validType="requiredcombo['pnl_edit-cbo_promoabrule_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Rule Code</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_promoabrule_code" class="easyui-textbox" mapping="promoabrule_code" uppercase="true" maxlength="3" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Level</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_promoablevel_id" class="easyui-combo" style="width: 400px" mapping="promoablevel_id" display="promoablevel_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Level harus diisi', disabled: true"   validType="requiredcombo['pnl_edit-cbo_promoablevel_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row blockseparator" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_promoabrule_ishasgroupa" class="easyui-checkbox c1" mapping="promoabrule_ishasgroupa" data-options="label: 'Group A', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row group-a group-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Rule Section</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_a_promoabrulesection_id" class="easyui-combo" style="width: 400px" mapping="a_promoabrulesection_id" display="a_promoabrulesection_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Rule section harus diisi'"   validType="requiredcombo['pnl_edit-cbo_a_promoabrulesection_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row group-a group-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Label</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_promoab_a_label" class="easyui-textbox" mapping="promoab_a_label"  maxlength="20" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Label harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row group-a group-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Disc (%)</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_promoab_a_disc" class="easyui-numberbox" mapping="promoab_a_disc" style="width: 400px; text-align:right" data-options="precision: 1, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row group-a group-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Qty Threshold</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_promoab_a_qtythreshold" class="easyui-numberbox" mapping="promoab_a_qtythreshold" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row group-a group-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Max Qty Applied</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_promoab_a_qtymax" class="easyui-numberbox" mapping="promoab_a_qtymax" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row group-a group-hidden" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_promoab_a_isreplacedisc" class="easyui-checkbox c1" mapping="promoab_a_isreplacedisc" data-options="label: 'Replace current discount', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_promoab_a_isblockonmeet" class="easyui-checkbox c1" mapping="promoab_a_isblockonmeet" data-options="label: 'Block on unmeet condition', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row blockseparator" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_promoabrule_ishasgroupb" class="easyui-checkbox c1" mapping="promoabrule_ishasgroupb" data-options="label: 'Group B', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row group-b group-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Rule Section</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_b_promoabrulesection_id" class="easyui-combo" style="width: 400px" mapping="b_promoabrulesection_id" display="b_promoabrulesection_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Rule section harus diisi'"   validType="requiredcombo['pnl_edit-cbo_b_promoabrulesection_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row group-b group-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Label</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_promoab_b_label" class="easyui-textbox" mapping="promoab_b_label"  maxlength="20" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Label harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row group-b group-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Disc (%)</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_promoab_b_disc" class="easyui-numberbox" mapping="promoab_b_disc" style="width: 400px; text-align:right" data-options="precision: 1, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row group-b group-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Qty Threshold</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_promoab_b_qtythreshold" class="easyui-numberbox" mapping="promoab_b_qtythreshold" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row group-b group-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Max Qty Applied</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_promoab_b_qtymax" class="easyui-numberbox" mapping="promoab_b_qtymax" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row group-b group-hidden" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_promoab_b_isreplacedisc" class="easyui-checkbox c1" mapping="promoab_b_isreplacedisc" data-options="label: 'Replace current discount', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row group-b group-hidden" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_promoab_b_isblockonmeet" class="easyui-checkbox c1" mapping="promoab_b_isblockonmeet" data-options="label: 'Block on unmeet condition', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/promoabmodel-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			
			
			
			
			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5 fgta-button-delete" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

