<div id="pnl_main" class="fullcontent page-panel posmain-container">
	<h5>Guests Book</h5>
	<div class="row">

		<div class="col s5">
			<div class="row">
				<div class="col s12 event-title">
					<span>event title</span> (<span>event id</span>)
				</div>
			</div>
			<div class="row">
				<div id="qr-reader" class="col s12" style="width: 100%"></div>
			</div>
			<div id="pnl_main-result" class="row">

			</div>
		</div>



		<div class="col s7">
			<div style="margin-left: 30px">	
			<div class="row">
				<div class="input-field col s12">
					<input id="pnl_main-obj_lineinput" placeholder="Scan MPC QRCode" type="text" class="validate">
					<label for="pnl_main-obj_lineinput">Scan MPC QRCode</label>
				</div>	
			</div>

			<div class="row">
				<div class="input-field col s11">
					<label>
						<input id="pnl_main-chk_ismanual" type="checkbox" class="filled-in" />
						<span>Manual Input</span>
					</label>
				</div>	
			</div>
			<div class="row">
				<div class="input-field col s11">
					<input id="pnl_main-obj_txt_nama" type="text" class="validate" style="text-transform: uppercase">
					<label for="pnl_main-obj_txt_nama">Nama</label>
				</div>	
			</div>
			<div class="row">
				<div class="input-field col s11">
					<input id="pnl_main-obj_txt_alamat" type="text" class="validate">
					<label for="pnl_main-obj_txt_alamat">Alamat</label>
				</div>	
			</div>
			<div class="row">
				<div class="input-field col s4">
					<input id="pnl_main-obj_txt_telp" type="number" class="validate">
					<label for="pnl_main-obj_txt_telp">No Telp</label>
				</div>	
				<div class="input-field col s7">
					<input id="pnl_main-obj_txt_email" type="email" class="validate" style="text-transform: lowercase">
					<label for="pnl_main-obj_txt_email">Email</label>
				</div>	
			</div>

			<div class="row">
				<div class="input-field col s4">	
					<button id="pnl_main-btn_save" class="waves-effect waves-light btn">Save</button>
				</div>
			</div>	
			</div>
		</div>

	</div>
	<div class="row">
		<div class="col s12">	
			<a href="javascript:void(0)" id="pnl_main-btn_display" class="lnkctr">Guestbook Display</a> |
			<a href="javascript:void(0)" id="pnl_main-btn_update" class="lnkctr">Update</a> |
			<a href="javascript:void(0)" id="pnl_main-btn_reload" class="lnkctr">Reload</a> |
		</div>
	</div>





</div>