<?php
require_once implode('/', [__DIR__, 'pos-secondmonitor.phtml']);
require_once implode('/', [__DIR__, 'posmain-entry.phtml']);
require_once implode('/', [__DIR__, 'posmain-payment.phtml']);
require_once implode('/', [__DIR__, 'posmain-itemlist.phtml']);
require_once implode('/', [__DIR__, 'posmain-member.phtml']);
require_once implode('/', [__DIR__, 'posmain-promo.phtml']);
require_once implode('/', [__DIR__, 'posmain-event.phtml']);
require_once implode('/', [__DIR__, 'posmain-staff.phtml']);
require_once implode('/', [__DIR__, 'posmain-table.phtml']);
require_once implode('/', [__DIR__, 'posmain-recall.phtml']);
