<div id="pnl_itemlist" class="fullcontent page-panel itemlist-container">
	<div style="display: flex; justify-content: space-between;">
		<div>
			<button id="pnl_itemlist-btn_back" class="waves-effect waves-light btn">Back</button>		
		</div>
		<div><h4 style="margin: 0px 0px 5px 0px">Item List</h4></div>
		<div>&nbsp;</div>
	</div>
	<div class="itemlist-gridpanel">
		<table id="pnl_itemlist-tbl_itemlist" class="highlight scroll">
			<thead>
				<tr>
					<th class="description">Item</th>
					<th class="valuecolumn">Price</th>
					<th class="lastcolumn">&nbsp;</th>
				</tr>
			</thead>

			<tbody style="height: calc(80vh);">
			</tbody>
		</table>
	</div>
	
	

</div>