<div id="pnl_promo" class="fullcontent page-panel">
	<div style="display: flex; justify-content: space-between;">
		<div>
			<button id="pnl_promo-btn_back" class="waves-effect waves-light btn" style="height: 40px"><i class="material-icons">arrow_back_ios_new</i></button>		
		</div>
		<div><h4 style="margin: 0px 0px 5px 0px">Promo</h4></div>
		<div>&nbsp;</div>
	</div>

	<div>

	
		<div class="promobuttonblock">
			<div class="promobuttonblock-col" style="width:150px; display: flex; justify-content: center; align-items: center;">
				<div id="pnl_promo-txt_promoactive_b1">not set</div>
			</div>
			<div class="promobuttonblock-col">
				<button id="pnl_promo-btn_resetb1" class="waves-effect waves-light btn orange accent-2">Reset</button>
			</div>
			<div class="promobuttonblock-col" id="pnl_promo-block-item">

			</div>
		</div>

		<div class="promobuttonblock">
			<div class="promobuttonblock-col" style="width:150px; display: flex; justify-content: center; align-items: center;">
				<div id="pnl_promo-txt_promoactive_b2">not set</div>
			</div>
			<div class="promobuttonblock-col">
				<button id="pnl_promo-btn_resetb2" class="waves-effect waves-light btn orange accent-2">Reset</button>
			</div>
			<div class="promobuttonblock-col" id="pnl_promo-block-subtotal">

			</div>
		</div>	

		<div class="promobuttonblock">
			<div class="promobuttonblock-col" style="width:150px; display: flex; justify-content: center; align-items: center;">
				<div id="pnl_promo-txt_promoactive_b3">not set</div>
			</div>
			<div class="promobuttonblock-col">
				<button id="pnl_promo-btn_resetb3" class="waves-effect waves-light btn orange accent-2">Reset</button>
			</div>
			<div class="promobuttonblock-col" id="pnl_promo-block-total">

			</div>
		</div>

	</div>
</div>