<?php require_once dirname(__FILE__).'/prorule-list.phtml' ?>
<?php require_once dirname(__FILE__).'/prorule-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/prorule-sectiongrid.phtml' ?>
<?php require_once dirname(__FILE__).'/prorule-sectionform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/prorule-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<?php } ?>
