<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Promo Rule</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_prorule_id" class="easyui-textbox" mapping="prorule_id" uppercase="true" maxlength="14" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'ID harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Level</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_prolevel_id" class="easyui-combo" style="width: 400px" mapping="prolevel_id" display="prolevel_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Level harus diisi'"   validType="requiredcombo['pnl_edit-cbo_prolevel_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Block</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_problock_id" class="easyui-combo" style="width: 400px" mapping="problock_id" display="problock_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Block harus diisi'"   validType="requiredcombo['pnl_edit-cbo_problock_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_prorule_name" class="easyui-textbox" mapping="prorule_name" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama Rule Promo harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_prorule_descr" class="easyui-textbox" mapping="prorule_descr"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Library</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_prorule_lib" class="easyui-textbox" mapping="prorule_lib"  maxlength="90" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama Library harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Function Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_prorule_fn" class="easyui-textbox" mapping="prorule_fn"  maxlength="90" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama Fungsi harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Spot</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_a_prospot_id" class="easyui-combo" style="width: 400px" mapping="a_prospot_id" display="a_prospot_name" data-options="editable:false, valueField:'id', textField:'text' , required: false, prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Step</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_a_prostep_id" class="easyui-combo" style="width: 400px" mapping="a_prostep_id" display="a_prostep_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Step harus diisi'"   validType="requiredcombo['pnl_edit-cbo_a_prostep_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col">Items Grouping</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_prorule_ishasgroupa" class="easyui-checkbox c1" mapping="prorule_ishasgroupa" data-options="label: 'Group A', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_prorule_ishasgroupb" class="easyui-checkbox c1" mapping="prorule_ishasgroupb" data-options="label: 'Group B', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col detilbox" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editsectiongrid')">
					<div id="pnl_edit-txt_section_title" class="detilgrid-text">Section</div>
					<div id="pnl_edit-txt_section_value" class="detilgrid-value">&nbsp;</div>
				</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/prorule-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			
			
			
			
			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5 fgta-button-delete" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

