<div id="pnl_list">
	<div class="fgta-page-title">Daftar Season</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<?php
		$customsearch = __DIR__.'/merchsea-list-customsearch.phtml'; 
		if (is_file($customsearch)) {
			include $customsearch;
		} else { ?>
		<!-- Simple Query -->
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
		<?php } ?>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			
			<?php
				$customview = __DIR__.'/merchsea-list-customview.phtml'; 
				if (is_file($customview)) {
					include $customview;
			} else { ?>
			<thead>
				<tr>
					<th mapping="merchsea_id">merchsea_id</th>
					<th mapping="merchsea_name">merchsea_name</th>
					<th mapping="merchsea_namedisplay">merchsea_namedisplay</th>
					<th mapping="merchsea_year" style="text-align: right"  formatter="row_format_number">merchsea_year</th>
					<th mapping="merchsea_yearmaxvisible" style="text-align: right"  formatter="row_format_number">merchsea_yearmaxvisible</th>
					<th mapping="merchsea_isdisabled" type="checkbox">merchsea_isdisabled</th>
					<th mapping="merchseagroup_name">merchseagroup_name</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Season</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Display Name</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Year</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Visible Until</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Disabled</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Season Group</td>

				</tr>
				</thead>
			<?php } ?>
			
		</table>
	</div>



</div>