<?php require_once dirname(__FILE__).'/merchitem-list.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitem-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitem-barcodegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitem-barcodeform.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitem-propgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitem-propform.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitem-channelgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitem-channelform.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitem-relatedgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitem-relatedform.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitem-picturegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitem-pictureform.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitem-refgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/merchitem-refform.phtml' ?>



