<div id="pnl_list">
	<div class="fgta-page-title">Daftar Item Merchandise</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<?php
		$customsearch = __DIR__.'/merchitem-list-customsearch.phtml'; 
		if (is_file($customsearch)) {
			include $customsearch;
		} else { ?>
		<!-- Simple Query -->
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
		<?php } ?>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<?php
				$customview = __DIR__.'/merchitem-list-customview.phtml'; 
				if (is_file($customview)) {
					include $customview;
				} else { ?>
				<tr>
					<th mapping="merchitem_id">merchitem_id</th>
					<th mapping="merchitem_art">merchitem_art</th>
					<th mapping="merchitem_mat">merchitem_mat</th>
					<th mapping="merchitem_col">merchitem_col</th>
					<th mapping="merchitem_size">merchitem_size</th>
					<th mapping="merchitem_name">merchitem_name</th>
					<th mapping="merchitem_price" style="text-align: right"  formatter="row_format_number">merchitem_price</th>
					<th mapping="merchitem_pricenett" style="text-align: right"  formatter="row_format_number">merchitem_pricenett</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ART</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">MAT</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">COL</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">SIZE</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Name</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Current Price</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Current Nett Price</td>

				</tr>
				<?php } ?>
			</thead>
		</table>
	</div>



</div>