create table rpt_sales (
	bon_id varchar(60) NOT NULL,
	bondetil_line int NOT NULL,
	bon_isvoid tinyint ,
	bon_date date,
	bon_time time,
	bon_year int,
	bon_month int,
	bon_ym varchar(7) ,
	bon_datestr varchar(10) ,
	bon_hour int,
	bon_week int ,
	bon_day int ,
	bon_event varchar(30) ,
	payment_id varchar(50) ,
	payment_name varchar(255) ,
	payment_bank varchar(50) ,
	payment_cardnumber varchar(40) ,
	payment_cardholder varchar(40) ,
	payment_value decimal(15,0) ,
	otherpayment_value decimal(15,0) ,
	machine_id varchar(10) ,
	bon_region_id varchar(5) ,
	region_id varchar(5) ,
	branch_id varchar(7) ,
	brand_name varchar(255) ,
	site_id varchar(50) ,
	site_name varchar(90) ,
	city_id varchar(30) ,
	area_id varchar(30) ,
	sitemodel_id varchar(10) ,
	location_id varchar(30) ,
	location_name varchar(100) ,
	salesperson_id varchar(10) ,
	salesperson_nik varchar(50) ,
	salesperson_name varchar(30) ,
	customer_id varchar(30) ,
	customer_telp varchar(30) ,
	customer_name varchar(30) ,
	customer_email varchar(50) ,
	heinv_id varchar(13) ,
	heinvitem_id varchar(13) ,
	heinvitem_barcode varchar(60) ,
	heinv_art varchar(30) ,
	heinv_mat varchar(30) ,
	heinv_col varchar(30) ,
	bondetil_size varchar(10) ,
	heinv_name varchar(255) ,
	heinv_iskonsinyasi tinyint ,
	heinvgro_id varchar(10) ,
	heinvgro_name varchar(30) ,
	heinvctg_id varchar(10) ,
	heinvctg_name varchar(50) ,
	heinvctg_costadd decimal(5,2) ,
	heinvctg_mf decimal(5,2) ,
	invcls_id varchar(8) ,
	invcls_name varchar(90) ,
	invcls_descr varchar(254) ,
	invcls_gro varchar(30) ,
	heinv_fit varchar(50) ,
	heinv_colordescr varchar(30) ,
	heinv_gender varchar(10) ,
	pcp_line varchar(50) ,
	pcp_gro varchar(50) ,
	pcp_ctg varchar(50) ,
	mdflag varchar(10) ,
	heinv_gtype varchar(10) ,
	season_group varchar(20) ,
	season_id varchar(10) ,
	heorder_id varchar(60) ,
	heinv_lastrvid varchar(60) ,
	heinv_lastrvdate date ,
	rvage int ,
	heinv_lasttrid varchar(60) ,
	heinv_lasttrdate date ,
	trage int ,
	promo_id varchar(10) ,
	promo_codenum varchar(30) ,
	promo_type varchar(10) ,
	promo_line varchar(10) ,
	promo_method varchar(50) ,
	promo_discp decimal(18,0) ,
	sales_qty int ,
	sales_itemgross decimal(15,0) ,
	sales_itemnett decimal(15,0) ,
	sales_nett decimal(15,0) ,
	currency_id varchar(10) ,
	heinv_fob decimal(17,2) ,
	heinv_lastcost decimal(17,2) ,
	cogs_estimated decimal(17,2) ,
	cogs_final decimal(17,2) ,
	PRIMARY key (bon_id, bondetil_line)
) ENGINE=MyISAM COMMENT='Table Report Sales';