drop table if exists `tmp_heinvreg`;
drop table if exists `tmp_heinvregitem`;


CREATE TABLE IF NOT EXISTS `tmp_heinvreg` (
	heinvreg_id varchar(30),
	heinvreg_date date,
	heinvreg_descr varchar(255),
	heinvreg_issizing tinyint,
	heinvreg_isposted tinyint,
	heinvreg_isgenerated tinyint,
	heinvreg_isseasonupdate tinyint,
	heinvreg_createby varchar(30),
	heinvreg_createdate datetime,
	heinvreg_modifyby varchar(30),
	heinvreg_modifydate datetime,
	heinvreg_postby varchar(30),
	heinvreg_postdate datetime,
	heinvreg_generateby varchar(30),
	heinvreg_generatedate datetime,
	heinvreg_type varchar(1),
	region_id varchar(30),
	branch_id varchar(30),
	season_id varchar(15),
	rekanan_id varchar(30),
	currency_id varchar(10),
	PRIMARY key(heinvreg_id)
) ENGINE=MyISAM COMMENT='Temporary Table untuk register item dari TransBrowser';



CREATE TABLE IF NOT EXISTS `tmp_heinvregitem` (
	heinvreg_id varchar(30),
	heinvregitem_line int ,
	heinv_id varchar(13),
	heinv_art varchar(30),
	heinv_mat varchar(30),
	heinv_col varchar(30),
	heinv_size varchar(30),
	heinv_barcode varchar(30),
	heinv_name varchar(40),
	heinv_descr varchar(50),
	heinv_box varchar(50),
	heinv_gtype varchar(50),
	heinv_produk varchar(50),
	heinv_bahan varchar(70),
	heinv_pemeliharaan varchar(100),
	heinv_logo varchar(30),
	heinv_dibuatdi varchar(30),
	heinv_other1 varchar(50),
	heinv_other2 varchar(50),
	heinv_other3 varchar(50),
	heinv_other4 varchar(50),
	heinv_other5 varchar(50),
	heinv_other6 varchar(50),
	heinv_other7 varchar(50),
	heinv_other8 varchar(50),
	heinv_other9 varchar(50),
	heinv_hscode_ship varchar(30),
	heinv_hscode_ina varchar(30),
	heinv_plbname varchar(100),
	heinv_price decimal(18,2),
	heinvitem_colnum varchar(5),
	heinvgro_id varchar(30),
	heinvctg_id varchar(30),
	heinvctg_sizetag varchar(50),
	branch_id varchar(30),
	heinv_isweb tinyint,
	heinv_weight decimal(5,2),
	heinv_length decimal(5,2),
	heinv_width decimal(5,2),
	heinv_height decimal(5,2),
	heinv_webdescr varchar(2500),
	invcls_id varchar(10),
	qty int,
	PRIMARY key(heinvreg_id, heinvregitem_line)
) ENGINE=MyISAM COMMENT='Temporary Table untuk register item dari TransBrowser';
